import { pickOne } from "../../lib/random";

/** Minimum a prompt can cost — the real price follows the process steps. */
export const PROMPT_COST = 1;

/** Mirrors the backend pricing: 1 credit per VISIBLE process step — exactly
    what the message meta shows ("7 steps" = 7 credits). A retry is 1 step = 1. */
export function promptCostFor(steps: number) {
  return Math.min(12, Math.max(1, steps));
}

/** The message always shows the persona intro + the plan + "Rendering…". */
export function visibleStepsFor(planLength: number) {
  return planLength + 2;
}

export const quickPrompts = [
  "@wiki Teach me something wonderfully random",
  "@smart Summarize a beautiful but useless idea",
  "@fast Give me a crisp satisfying answer",
  "@deep Analyze this coffee like a product strategy",
  "@lorem Make this sound unusually polished",
];

export const processingSteps = [
  "Reading context...",
  "Allocating simulated tokens...",
  "Consulting the simulated agent...",
  "Polishing the response...",
  "Adding a quiet layer of confidence...",
  "Simulating deep reasoning...",
];

export function getProcessingPlan(prompt: string): string[] {
  if (prompt.includes("@fast")) {
    return ["Prioritizing the request...", "Preparing a fast answer..."];
  }

  if (prompt.includes("@deep")) {
    return [
      "Expanding implications...",
      "Searching for simulated depth...",
      "Polishing the conclusion...",
    ];
  }

  // Random depth: prompts never drain the exact same credits twice.
  // 2–3 plan steps + intro + rendering = 4–5 visible steps ⇒ 4–5 credits.
  return Array.from({ length: 2 + Math.floor(Math.random() * 2) }, () => pickOne(processingSteps));
}

export function generateFakeResponse(prompt: string): string {
  const normalized = prompt.toLowerCase();

  if (normalized.includes("code") || normalized.includes("react") || normalized.includes("tauri")) {
    return "Simulated dev advice: start with readable local state, give immediate feedback for every action, then make the architecture look like it expected this all along.";
  }

  if (normalized.includes("bouton") || normalized.includes("design")) {
    return "Simulated premium analysis: this button needs a fine balance between intent, visual weight, and micro-feedback. A 14% shadow can change the fate of a session.";
  }

  if (normalized.includes("@wiki")) {
    return "Simulated encyclopedia excerpt: satisfaction systems often combine credits, progress, and motion to make small actions feel meaningfully complete.";
  }

  if (normalized.includes("@lorem")) {
    return "Premium lorem ipsum: polite, confident, slightly mysterious, with a hint of productivity and zero false promise.";
  }

  return pickOne([
    "I processed that with a simulated high-cost model. The idea holds together, especially if every action gives immediate and tasteful feedback.",
    "Simulation complete. The next move is to make the action instant, the progress visible, and the result oddly satisfying.",
    "Generated by an agent that is intentionally simulated: turn the intent into a small interactive moment, then make it feel polished enough to repeat.",
  ]);
}
